package frc.robot.controlboard;

public enum ButtonCommand {
  INVERT_DRIVING,
  SHIFT_DRIVETRAIN,
  MANUAL_RUN_INTAKE,
  INTAKE,
  INTAKE_EXTENDER_MOTION_MAGIC,
  EXTEND_INTAKE,
  MANUAL_RUN_MAGAZINE,
  AUTO_REFILL_QUEUE,
  MANUAL_RUN_QUEUE,
  AUTO_FEED_SHOOTER,
  AUTO_RUN_SHOOTER,
  AUTO_AIM_TURRET,
  AUTO_SHOOT, MANUAL_REVERSE_MAGAZINE, MANUAL_REVERSE_QUEUE
}
